name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12 ]
        include:
          - os: ubuntu-22.04
            cmake-prefix-path: /usr/lib/llvm-14
          - os: macos-12
            cmake-prefix-path: /usr/local/opt/llvm@14
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install liblld-14-dev
        fi
      shell: bash

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=${{matrix.cmake-prefix-path}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run tests
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          ${{github.workspace}}/build/test/test
        fi
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: ${{runner.os}}-fcc
        path: ${{github.workspace}}/build/fcc
