name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ]
        include:
          - os: ubuntu-20.04
            cmake-prefix-path: /usr/lib/llvm-13
          - os: macos-11
            cmake-prefix-path: /usr/local/opt/llvm@13
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo ''
        elif [ "$RUNNER_OS" == "Linux" ]; then
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - &&
          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main" | sudo tee -a /etc/apt/sources.list &&
          echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main" | sudo tee -a /etc/apt/sources.list &&
          sudo apt-get update && sudo apt-get install llvm-13-dev liblld-13-dev antlr4 libantlr4-runtime-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install antlr antlr4-cpp-runtime
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=${{matrix.cmake-prefix-path}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v3
      with:
        name: ${{runner.os}}-fcc
        path: ${{github.workspace}}/build/fcc
